name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  buildlib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/scllib
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        working-directory: ./projects/scllib
        run: npm install && npm run package
      - name: Publish package on NPM 📦
        run: |
          cd ../../dist/scllib
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}