name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  buildlib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install global dependencies 🔧
        run: rm package-lock.json && npm install
      - name: Install Lib dependencies an Build 🔧
        run: |
            npm install -g @angular/cli > /dev/null
            ng config -g cli.warnings.versionMismatch false
            npm run build-lib
      - name: Publish package on NPM 📦
        run: |
          cd dist/scllib 
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}